export interface ProjectAmenity {
  name: string;
  image: string;
}

export interface Project {
  slug: string;
  name: string;
  tag: string;
  type: string;
  area: string;
  price: string;
  image: string;
  description?: string;
  highlights?: string[];
  // Extended for detail page
  location?: string;
  priceDisplay?: string;
  reraNumber?: string;
  reraUrl?: string;
  possessionDate?: string;
  projectArea?: string;
  longDescription?: string;
  galleryImages?: string[];
  amenities?: ProjectAmenity[];
}

const RERA_URL = "https://www.gujrera.gujarat.gov.in/";
const AMENITY_IMAGES = [
  "https://images.unsplash.com/photo-1585320806297-9794b3e4ee0e?w=200&q=80",
  "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=200&q=80",
  "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=200&q=80",
  "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=200&q=80",
  "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=200&q=80",
  "https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=200&q=80",
];

const defaultAmenities: ProjectAmenity[] = [
  { name: "Landscaped Gardens", image: AMENITY_IMAGES[0] },
  { name: "Kids Play Area", image: AMENITY_IMAGES[1] },
  { name: "Clubhouse", image: AMENITY_IMAGES[2] },
  { name: "Swimming Pool", image: AMENITY_IMAGES[5] },
  { name: "Fitness Centre", image: AMENITY_IMAGES[4] },
  { name: "Multi-purpose Court", image: AMENITY_IMAGES[3] },
];

// Project images in public/images/projects/<slug>.png (or .jpg)
const PROJECT_IMG = (slug: string) => `/images/projects/${slug}.png`;

export const projects: Project[] = [
  {
    slug: "the-west-park",
    name: "The West Park",
    tag: "Ready to Move",
    type: "Villas",
    area: "Starting 3,853.48 Sq. Ft.",
    price: "Available on Request",
    priceDisplay: "Available on Request",
    image: PROJECT_IMG("the-west-park"),
    location: "SG Highway, Ahmedabad – Gandhinagar, Gujarat",
    reraNumber: "PR/GJ/GANDHINAGAR/GANDHINAGAR/AUDA/RAA10801/201022",
    reraUrl: RERA_URL,
    possessionDate: "Ready to move",
    description: "Luxury villas in the heart of Shantigram. Ready to move with premium finishes.",
    longDescription: "The West Park offers premium villas with expansive living spaces, private gardens, and world-class finishes. Contemporary two-storey villas feature large glass doors, wooden decks, and private pools set in lush tropical landscaping. RERA registered, ready for possession.",
    highlights: ["Private pool & deck", "Gated community", "24×7 security"],
    amenities: defaultAmenities,
  },
  {
    slug: "ambrosia",
    name: "Ambrosia",
    tag: "Under Construction",
    type: "4 BHK Ultra-Luxury Apartments",
    area: "1,671.6 – 1,902.19 Sq. Ft.",
    price: "₹ 2.49 Cr* onwards",
    priceDisplay: "₹ 2.49 Cr* onwards",
    image: PROJECT_IMG("ambrosia"),
    location: "SG Highway, Ahmedabad – Gandhinagar, Gujarat",
    reraNumber: "PR/GJ/GANDHINAGAR/GANDHINAGAR/AUDA/RAA10833/201022",
    reraUrl: RERA_URL,
    possessionDate: "Under construction",
    description: "Ultra-luxury 4 BHK apartments with world-class amenities.",
    longDescription: "Ambrosia offers ultra-luxurious 4 BHK residences with smart home solutions, infinity pool, and concierge services.",
    highlights: ["Smart homes", "Infinity pool", "Concierge"],
    amenities: defaultAmenities,
  },
  {
    slug: "the-north-park",
    name: "The North Park",
    tag: "Under Construction",
    type: "4 BHK Villas",
    area: "3,374.81 – 3,791.26 Sq. Ft.",
    price: "Available on Request",
    priceDisplay: "Available on Request",
    image: PROJECT_IMG("the-north-park"),
    location: "SG Highway, Ahmedabad – Gandhinagar, Gujarat",
    reraNumber: "PR/GJ/GANDHINAGAR/GANDHINAGAR/AUDA/RAA10815/201022",
    reraUrl: RERA_URL,
    possessionDate: "Under construction",
    description: "Spacious 4 BHK villas with modern architecture.",
    longDescription: "The North Park brings you 4 BHK villas set in lush greenery with premium fittings and private gardens.",
    highlights: ["Private gardens", "Premium fittings", "RERA registered"],
    amenities: defaultAmenities,
  },
  {
    slug: "belrosa",
    name: "Belrosa",
    tag: "Under Construction",
    type: "4 & 5 BHK Apartment | 5 & 6 BHK Duplex",
    area: "4 BHK: 2,942.23 Sq. Ft. onwards",
    price: "Available on Request",
    priceDisplay: "Available on Request",
    image: PROJECT_IMG("belrosa"),
    location: "SG Highway, Ahmedabad – Gandhinagar, Gujarat",
    reraNumber: "PR/GJ/GANDHINAGAR/GANDHINAGAR/AUDA/RAA10822/201022",
    reraUrl: RERA_URL,
    possessionDate: "Under construction",
    description: "Apartments and duplexes for discerning homeowners.",
    longDescription: "Belrosa offers 4 & 5 BHK apartments and 5 & 6 BHK duplexes with premium lobby and clubhouse access.",
    highlights: ["Duplex options", "Premium lobby", "Clubhouse access"],
    amenities: defaultAmenities,
  },
  {
    slug: "paarijat",
    name: "Paarijat",
    tag: "Ready to Move",
    type: "4 BHK Premium Homes",
    area: "1,405 – 1,608 Sq. Ft.",
    price: "₹ 2.36 Cr onwards",
    priceDisplay: "₹ 2.36 Cr onwards",
    image: PROJECT_IMG("paarijat"),
    location: "SG Highway, Ahmedabad – Gandhinagar, Gujarat",
    reraNumber: "PR/GJ/GANDHINAGAR/GANDHINAGAR/AUDA/RAA10798/201022",
    reraUrl: RERA_URL,
    possessionDate: "Ready to move",
    description: "4 BHK premium homes with contemporary design. Ready for possession.",
    longDescription: "Paarijat delivers 4 BHK premium homes ready for possession with modular kitchen and spacious balconies.",
    highlights: ["Ready possession", "Modular kitchen", "Balconies"],
    amenities: defaultAmenities,
  },
  {
    slug: "greenfield",
    name: "Greenfield",
    tag: "Under Construction",
    type: "3 BHK Apartment & 4 BHK Penthouse",
    area: "1,277.89 – 2,163.33 Sq. Ft.",
    price: "₹ 1.73 Cr onwards",
    priceDisplay: "₹ 1.73 Cr onwards",
    image: PROJECT_IMG("greenfield"),
    location: "SG Highway, Ahmedabad – Gandhinagar, Gujarat",
    reraNumber: "PR/GJ/GANDHINAGAR/GANDHINAGAR/AUDA/RAA10841/201022",
    reraUrl: RERA_URL,
    possessionDate: "Under construction",
    description: "3 BHK apartments and 4 BHK penthouses with green views.",
    longDescription: "Greenfield offers 3 BHK apartments and 4 BHK penthouses with views of the green belt and modern amenities.",
    highlights: ["Penthouse option", "Green belt view", "Affordable luxury"],
    amenities: defaultAmenities,
  },
  {
    slug: "the-storeys-golf-coast",
    name: "The Storeys Golf Coast",
    tag: "Under Construction",
    type: "4 BHK Simplex & 5 BHK Duplex",
    area: "3,500.74 – 6,466.41 Sq. Ft.",
    price: "Available on Request",
    priceDisplay: "Available on Request",
    image: PROJECT_IMG("the-storeys-golf-coast"),
    location: "SG Highway, Ahmedabad – Gandhinagar, Gujarat",
    reraNumber: "PR/GJ/GANDHINAGAR/GANDHINAGAR/AUDA/RAA10855/201022",
    reraUrl: RERA_URL,
    possessionDate: "Under construction",
    description: "Homes overlooking the golf course with premium finishes.",
    longDescription: "The Storeys Golf Coast offers 4 BHK simplex and 5 BHK duplex homes overlooking the golf course.",
    highlights: ["Golf view", "Duplex available", "High ceilings"],
    amenities: defaultAmenities,
  },
  {
    slug: "skyline",
    name: "Skyline",
    tag: "Under Construction",
    type: "4 BHK Uberments",
    area: "1,479.28 – 2,349.76 Sq. Ft.",
    price: "₹ 1.95 Cr onwards",
    priceDisplay: "₹ 1.95 Cr onwards",
    image: PROJECT_IMG("skyline"),
    location: "SG Highway, Ahmedabad – Gandhinagar, Gujarat",
    reraNumber: "PR/GJ/GANDHINAGAR/GANDHINAGAR/AUDA/RAA10862/201022",
    reraUrl: RERA_URL,
    possessionDate: "Under construction",
    description: "4 BHK uberments with smart living features.",
    longDescription: "Skyline offers 4 BHK uberments with smart living features and skyline views.",
    highlights: ["Skyline views", "Modern design", "Central location"],
    amenities: defaultAmenities,
  },
  {
    slug: "embrace",
    name: "Embrace",
    tag: "Under Construction",
    type: "3 BHK Lifestyle Homes",
    area: "987.91 – 2,238.14 Sq. Ft.",
    price: "₹ 1.42 Cr onwards",
    priceDisplay: "₹ 1.42 Cr onwards",
    image: PROJECT_IMG("embrace"),
    location: "SG Highway, Ahmedabad – Gandhinagar, Gujarat",
    reraNumber: "PR/GJ/GANDHINAGAR/GANDHINAGAR/AUDA/RAA10870/201022",
    reraUrl: RERA_URL,
    possessionDate: "Under construction",
    description: "3 BHK lifestyle homes for young families.",
    longDescription: "Embrace offers 3 BHK lifestyle homes with a central landscaped courtyard, swimming pool, children's play area, and communal lawns. Modern towers with contemporary design and family-friendly amenities within Shantigram.",
    highlights: ["Swimming pool", "Kids play area", "Central courtyard"],
    amenities: defaultAmenities,
  },
  {
    slug: "greenview",
    name: "Greenview",
    tag: "RERA",
    type: "3 & 4 BHK + WFH Apartments",
    area: "1,190.17 – 1,955.80 Sq. Ft.",
    price: "₹ 1.62 Cr Onwards",
    priceDisplay: "₹ 1.62 Cr Onwards",
    image: PROJECT_IMG("greenview"),
    location: "SG Highway, Ahmedabad – Gandhinagar, Gujarat",
    reraNumber: "PR/GJ/GANDHINAGAR/GANDHINAGAR/AUDA/RAA10875/201022",
    reraUrl: RERA_URL,
    description: "3 & 4 BHK apartments with work-from-home friendly layouts.",
    longDescription: "Greenview offers 3 & 4 BHK + WFH apartments in modern high-rises with balconies featuring integrated greenery and vertical gardens. Contemporary design with brown wood-textured railings and landscaped road frontage.",
    highlights: ["Green balconies", "WFH friendly", "Modern towers"],
    amenities: defaultAmenities,
  },
  {
    slug: "aster-neo",
    name: "Aster NEO",
    tag: "Ready to Move",
    type: "2 BHK #Smartments",
    area: "634.85 Sq. Ft.",
    price: "₹ 78 lakhs onwards",
    priceDisplay: "₹ 78 lakhs onwards",
    image: PROJECT_IMG("aster-neo"),
    location: "SG Highway, Ahmedabad – Gandhinagar, Gujarat",
    reraNumber: "PR/GJ/GANDHINAGAR/GANDHINAGAR/AUDA/RAA10880/201022",
    reraUrl: RERA_URL,
    possessionDate: "Ready to move",
    description: "2 BHK smartments ready for possession.",
    longDescription: "Aster NEO offers compact 2 BHK #Smartments with smart living features, ready to move.",
    highlights: ["Ready to move", "Smart homes", "Compact living"],
    amenities: defaultAmenities,
  },
  {
    slug: "ikaria",
    name: "Ikaria",
    tag: "Ready to Move",
    type: "1 & 2 BHK Senior Friendly Homes",
    area: "580.60 – 858.52 Sq. Ft.",
    price: "₹ 87 Lacs onwards",
    priceDisplay: "₹ 87 Lacs onwards",
    image: PROJECT_IMG("ikaria"),
    location: "SG Highway, Ahmedabad – Gandhinagar, Gujarat",
    reraNumber: "PR/GJ/GANDHINAGAR/GANDHINAGAR/AUDA/RAA10885/201022",
    reraUrl: RERA_URL,
    possessionDate: "Ready to move",
    description: "1 & 2 BHK senior-friendly homes.",
    longDescription: "Ikaria offers 1 & 2 BHK senior-friendly homes designed for comfort and accessibility.",
    highlights: ["Senior friendly", "Ready to move", "Accessible design"],
    amenities: defaultAmenities,
  },
  {
    slug: "elysium-novus",
    name: "Elysium Novus",
    tag: "Under Construction",
    type: "3 & 2 BHK Homes",
    area: "668.43 – 1,016.01 Sq. Ft.",
    price: "₹ 1.15 Cr* onwards",
    priceDisplay: "₹ 1.15 Cr* onwards",
    image: PROJECT_IMG("elysium-novus"),
    location: "SG Highway, Ahmedabad – Gandhinagar, Gujarat",
    reraNumber: "PR/GJ/GANDHINAGAR/GANDHINAGAR/AUDA/RAA10890/201022",
    reraUrl: RERA_URL,
    possessionDate: "Under construction",
    description: "3 & 2 BHK homes with modern amenities.",
    longDescription: "Elysium Novus offers 3 & 2 BHK homes with contemporary design and township connectivity.",
    highlights: ["Modern design", "Township", "Value homes"],
    amenities: defaultAmenities,
  },
  {
    slug: "water-lily",
    name: "Water Lily",
    tag: "RERA",
    type: "5 BHK Duplex Penthouses",
    area: "4,388.98 Sq. Ft.",
    price: "Available on Request",
    priceDisplay: "Available on Request",
    image: PROJECT_IMG("water-lily"),
    location: "SG Highway, Ahmedabad – Gandhinagar, Gujarat",
    reraNumber: "PR/GJ/GANDHINAGAR/GANDHINAGAR/AUDA/RAA10895/201022",
    reraUrl: RERA_URL,
    description: "5 BHK duplex penthouses with premium finishes.",
    longDescription: "Water Lily offers 5 BHK duplex penthouses with serene waterside views. The project features a decorative bridge over turquoise water, lush palm-lined banks, and a tranquil setting ideal for luxury living. Expansive layouts with premium finishes.",
    highlights: ["Waterside living", "Bridge & canal views", "Duplex penthouses"],
    amenities: defaultAmenities,
  },
  {
    slug: "la-marina",
    name: "La Marina",
    tag: "RERA",
    type: "4 BHK & 5 BHK Penthouses",
    area: "2,002.09 – 3,831.9 Sq. Ft.",
    price: "Available on Request",
    priceDisplay: "Available on Request",
    image: PROJECT_IMG("la-marina"),
    location: "SG Highway, Ahmedabad – Gandhinagar, Gujarat",
    reraNumber: "PR/GJ/GANDHINAGAR/GANDHINAGAR/AUDA/RAA10900/201022",
    reraUrl: RERA_URL,
    description: "4 BHK & 5 BHK penthouses with waterfront living.",
    longDescription: "La Marina offers 4 BHK & 5 BHK penthouses with striking waterfront views. Modern towers with artistic lighting, calm water frontage, and premium finishes. Ideal for those seeking a serene yet connected address within Shantigram.",
    highlights: ["Waterfront views", "Premium penthouses", "Modern design"],
    amenities: defaultAmenities,
  },
  {
    slug: "the-storeys",
    name: "The Storeys",
    tag: "RERA",
    type: "4/5 BHK Single-Storeyed Homes & Duplex Homes",
    area: "3,541.76 – 5,997.76 Sq. Ft.",
    price: "Available on Request*",
    priceDisplay: "Available on Request* onwards",
    image: PROJECT_IMG("the-storeys"),
    location: "SG Highway, Ahmedabad – Gandhinagar, Gujarat",
    reraNumber: "PR/GJ/GANDHINAGAR/GANDHINAGAR/AUDA/RAA10905/201022",
    reraUrl: RERA_URL,
    description: "4/5 BHK single-storeyed and duplex homes.",
    longDescription: "The Storeys offers 4/5 BHK single-storeyed and duplex homes with views of the golf course and township. Rooftop lounges, landscaped villas, and direct access to the green fairways define this premium address.",
    highlights: ["Golf course views", "Single-storey & duplex", "Rooftop lounges"],
    amenities: defaultAmenities,
  },
  {
    slug: "amogha",
    name: "Amogha",
    tag: "RERA",
    type: "3 BHK Apartments",
    area: "624.09 – 776.40 Sq. Ft.",
    price: "₹ 1.04 Cr.* onwards",
    priceDisplay: "₹ 1.04 Cr.* onwards",
    image: PROJECT_IMG("amogha"),
    location: "SG Highway, Ahmedabad – Gandhinagar, Gujarat",
    reraNumber: "PR/GJ/GANDHINAGAR/GANDHINAGAR/AUDA/RAA10910/201022",
    reraUrl: RERA_URL,
    description: "3 BHK apartments with compact, efficient layouts.",
    longDescription: "Amogha offers 3 BHK apartments with modern design and township amenities.",
    highlights: ["Compact 3 BHK", "Value", "Township"],
    amenities: defaultAmenities,
  },
  {
    slug: "the-meadows",
    name: "The Meadows",
    tag: "RERA",
    type: "2, 2.5, 3 BHK",
    area: "661.33 – 1,349.04 Sq. Ft.",
    price: "Available on Request",
    priceDisplay: "Available on Request",
    image: PROJECT_IMG("the-meadows"),
    location: "SG Highway, Ahmedabad – Gandhinagar, Gujarat",
    reraNumber: "PR/GJ/GANDHINAGAR/GANDHINAGAR/AUDA/RAA10915/201022",
    reraUrl: RERA_URL,
    description: "2, 2.5 & 3 BHK homes in a green setting.",
    longDescription: "The Meadows offers 2, 2.5 & 3 BHK homes around a large, well-maintained green field with sports ground and recreational space. Buildings overlook the open lawn—ideal for families who value outdoor play and community living.",
    highlights: ["Green field & sports ground", "Multiple configurations", "Family-friendly"],
    amenities: defaultAmenities,
  },
  {
    slug: "elysium",
    name: "Elysium",
    tag: "RERA",
    type: "2, 2.5 BHK",
    area: "660.15 – 839.5 Sq. Ft.",
    price: "Available on Request",
    priceDisplay: "Available on Request",
    image: PROJECT_IMG("elysium"),
    location: "SG Highway, Ahmedabad – Gandhinagar, Gujarat",
    reraNumber: "PR/GJ/GANDHINAGAR/GANDHINAGAR/AUDA/RAA10920/201022",
    reraUrl: RERA_URL,
    description: "2 & 2.5 BHK homes with contemporary design.",
    longDescription: "Elysium offers 2 & 2.5 BHK homes with modern amenities and township connectivity.",
    highlights: ["Compact", "Contemporary", "Township"],
    amenities: defaultAmenities,
  },
  {
    slug: "aster",
    name: "Aster",
    tag: "RERA",
    type: "2 BHK Apartments",
    area: "634.85 – 641.52 Sq. Ft.",
    price: "₹ 78 Lakh* onwards",
    priceDisplay: "₹ 78 Lakh* onwards",
    image: PROJECT_IMG("aster"),
    location: "SG Highway, Ahmedabad – Gandhinagar, Gujarat",
    reraNumber: "PR/GJ/GANDHINAGAR/GANDHINAGAR/AUDA/RAA10925/201022",
    reraUrl: RERA_URL,
    description: "2 BHK apartments with smart living.",
    longDescription: "Aster offers 2 BHK apartments behind a grand, well-lit entrance with security cabin, contemporary gate design, and lush landscaping. Modern high-rises with balconies and a secure, gated community feel.",
    highlights: ["Grand entrance", "24×7 security cabin", "Gated community"],
    amenities: defaultAmenities,
  },
  {
    slug: "aangan-ahmedabad",
    name: "Aangan Ahmedabad",
    tag: "RERA",
    type: "1 & 2 BHK Apartments",
    area: "527.43 Sq. Ft.",
    price: "Available on Request",
    priceDisplay: "Available on Request",
    image: PROJECT_IMG("aangan-ahmedabad"),
    location: "SG Highway, Ahmedabad – Gandhinagar, Gujarat",
    reraNumber: "PR/GJ/GANDHINAGAR/GANDHINAGAR/AUDA/RAA10930/201022",
    reraUrl: RERA_URL,
    description: "1 & 2 BHK apartments for first-time buyers.",
    longDescription: "Aangan Ahmedabad offers 1 & 2 BHK apartments around a central, well-manicured garden with palm trees, pathways, and a children's play area. Courtyard-style layout with modern facades and family-friendly green spaces.",
    highlights: ["Central garden", "Palm trees & play area", "Starter homes"],
    amenities: defaultAmenities,
  },
  {
    slug: "center-point",
    name: "Center Point",
    tag: "Ready to Move",
    type: "Shops & Showrooms",
    area: "300 Sq. Ft. onwards",
    price: "Available on Lease",
    priceDisplay: "Available on Lease",
    image: PROJECT_IMG("center-point"),
    location: "SG Highway, Ahmedabad – Gandhinagar, Gujarat",
    reraNumber: "PR/GJ/GANDHINAGAR/GANDHINAGAR/AUDA/RAA10935/201022",
    reraUrl: RERA_URL,
    possessionDate: "Ready to move",
    description: "Shops and showrooms in the heart of Shantigram. Ready to move.",
    longDescription: "Center Point is a multi-level retail and entertainment destination with cinema, Game Zone, fashion and lifestyle stores, cafes, and food outlets. Well-lit at night with parking and landscaped access. Available on lease, ready for business.",
    highlights: ["Cinema & Game Zone", "Retail & dining", "Ready on lease"],
    amenities: defaultAmenities,
  },
  {
    slug: "inspire-corporate-capital",
    name: "Inspire Corporate Capital",
    tag: "RERA",
    type: "Work Spaces",
    area: "274.47 – 12,013.28 Sq. Ft.",
    price: "₹ 3.03 Cr.",
    priceDisplay: "₹ 3.03 Cr.",
    image: PROJECT_IMG("inspire-corporate-capital"),
    location: "SG Highway, Ahmedabad – Gandhinagar, Gujarat",
    reraNumber: "PR/GJ/GANDHINAGAR/GANDHINAGAR/AUDA/RAA10940/201022",
    reraUrl: RERA_URL,
    description: "Work spaces and commercial offices.",
    longDescription: "Inspire Corporate Capital offers premium work spaces in sleek glass-fronted towers with green terraces, sun-shading fins, and contemporary design. Integrated with landscaped pathways and modern urban infrastructure within Shantigram.",
    highlights: ["Glass-fronted towers", "Green terraces", "Premium work spaces"],
    amenities: defaultAmenities,
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}
